name: Move assigned and review_requested pull requests into Todo

on:
  pull_request:
    types: [assigned, review_requested]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ATM Project
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
