name: Reuse existing workflow - npm run cypress:headless

on:
  push:
    branches: [ "main", "staging" ]
  workflow_dispatch:

jobs:
  steps:
      uses: Rise-io/atm-dawn/.github/workflows/npm-build-cypress-headless-test.yml@staging
